import type { MarseilleDeck } from "../types/decks";

export const marseilleDeck: MarseilleDeck[] = [
	{ name: "The Conjurer", image: "./marseille-deck/a01.jpg" },
	{ name: "The Popess", image: "./marseille-deck/a02.jpg" },
	{ name: "The Empress", image: "./marseille-deck/a03.jpg" },
	{ name: "The Emperor", image: "./marseille-deck/a04.jpg" },
	{ name: "The Pope", image: "./marseille-deck/a05.jpg" },
	{ name: "The Lovers", image: "./marseille-deck/a06.jpg" },
	{ name: "The Chariot", image: "./marseille-deck/a07.jpg" },
	{ name: "Justice", image: "./marseille-deck/a08.jpg" },
	{ name: "The Hermit", image: "./marseille-deck/a09.jpg" },
	{ name: "The Wheel of Fortune", image: "./marseille-deck/a10.jpg" },
	{ name: "Strength", image: "./marseille-deck/a11.jpg" },
	{ name: "The Hanged Man", image: "./marseille-deck/a12.jpg" },
	{ name: "Death", image: "./marseille-deck/a13.jpg" },
	{ name: "Temperance", image: "./marseille-deck/a14.jpg" },
	{ name: "The Devil", image: "./marseille-deck/a15.jpg" },
	{ name: "The Tower of God", image: "./marseille-deck/a16.jpg" },
	{ name: "The Star", image: "./marseille-deck/a17.jpg" },
	{ name: "The Moon", image: "./marseille-deck/a18.jpg" },
	{ name: "The Sun", image: "./marseille-deck/a19.jpg" },
	{ name: "The Last Judgment", image: "./marseille-deck/a20.jpg" },
	{ name: "The World", image: "./marseille-deck/a21.jpg" },
	{ name: "The Fool", image: "./marseille-deck/a22.jpg" },
	{ name: "Ace of Clubs", image: "./marseille-deck/b01.jpg" },
	{ name: "Two of Clubs", image: "./marseille-deck/b02.jpg" },
	{ name: "Three of Clubs", image: "./marseille-deck/b03.jpg" },
	{ name: "Four of Clubs", image: "./marseille-deck/b04.jpg" },
	{ name: "Five of Clubs", image: "./marseille-deck/b05.jpg" },
	{ name: "Six of Clubs", image: "./marseille-deck/b06.jpg" },
	{ name: "Seven of Clubs", image: "./marseille-deck/b07.jpg" },
	{ name: "Eight of Clubs", image: "./marseille-deck/b08.jpg" },
	{ name: "Nine of Clubs", image: "./marseille-deck/b09.jpg" },
	{ name: "Ten of Clubs", image: "./marseille-deck/b10.jpg" },
	{ name: "Page of Clubs", image: "./marseille-deck/b11.jpg" },
	{ name: "Knight of Clubs", image: "./marseille-deck/b12.jpg" },
	{ name: "Queen of Clubs", image: "./marseille-deck/b13.jpg" },
	{ name: "King of Clubs", image: "./marseille-deck/b14.jpg" },
	{ name: "Ace of Cups", image: "./marseille-deck/c01.jpg" },
	{ name: "Two of Cups", image: "./marseille-deck/c02.jpg" },
	{ name: "Three of Cups", image: "./marseille-deck/c03.jpg" },
	{ name: "Four of Cups", image: "./marseille-deck/c04.jpg" },
	{ name: "Five of Cups", image: "./marseille-deck/c05.jpg" },
	{ name: "Six of Cups", image: "./marseille-deck/c06.jpg" },
	{ name: "Seven of Cups", image: "./marseille-deck/c07.jpg" },
	{ name: "Eight of Cups", image: "./marseille-deck/c08.jpg" },
	{ name: "Nine of Cups", image: "./marseille-deck/c09.jpg" },
	{ name: "Ten of Cups", image: "./marseille-deck/c10.jpg" },
	{ name: "Page of Cups", image: "./marseille-deck/c11.jpg" },
	{ name: "Knight of Cups", image: "./marseille-deck/c12.jpg" },
	{ name: "Queen of Cups", image: "./marseille-deck/c13.jpg" },
	{ name: "King of Cups", image: "./marseille-deck/c14.jpg" },
	{ name: "Ace of Coins", image: "./marseille-deck/d01.jpg" },
	{ name: "Two of Coins", image: "./marseille-deck/d02.jpg" },
	{ name: "Three of Coins", image: "./marseille-deck/d03.jpg" },
	{ name: "Four of Coins", image: "./marseille-deck/d04.jpg" },
	{ name: "Five of Coins", image: "./marseille-deck/d05.jpg" },
	{ name: "Six of Coins", image: "./marseille-deck/d06.jpg" },
	{ name: "Seven of Coins", image: "./marseille-deck/d07.jpg" },
	{ name: "Eight of Coins", image: "./marseille-deck/d08.jpg" },
	{ name: "Nine of Coins", image: "./marseille-deck/d09.jpg" },
	{ name: "Ten of Coins", image: "./marseille-deck/d10.jpg" },
	{ name: "Page of Coins", image: "./marseille-deck/d11.jpg" },
	{ name: "Knight of Coins", image: "./marseille-deck/d12.jpg" },
	{ name: "Queen of Coins", image: "./marseille-deck/d13.jpg" },
	{ name: "King of Coins", image: "./marseille-deck/d14.jpg" },
	{ name: "Ace of Swords", image: "./marseille-deck/e01.jpg" },
	{ name: "Two of Swords", image: "./marseille-deck/e02.jpg" },
	{ name: "Three of Swords", image: "./marseille-deck/e03.jpg" },
	{ name: "Four of Swords", image: "./marseille-deck/e04.jpg" },
	{ name: "Five of Swords", image: "./marseille-deck/e05.jpg" },
	{ name: "Six of Swords", image: "./marseille-deck/e06.jpg" },
	{ name: "Seven of Swords", image: "./marseille-deck/e07.jpg" },
	{ name: "Eight of Swords", image: "./marseille-deck/e08.jpg" },
	{ name: "Nine of Swords", image: "./marseille-deck/e09.jpg" },
	{ name: "Ten of Swords", image: "./marseille-deck/e10.jpg" },
	{ name: "Page of Swords", image: "./marseille-deck/e11.jpg" },
	{ name: "Knight of Swords", image: "./marseille-deck/e12.jpg" },
	{ name: "Queen of Swords", image: "./marseille-deck/e13.jpg" },
	{ name: "King of Swords", image: "./marseille-deck/e14.jpg" }
];

export const marseilleCardBack: MarseilleDeck[] = [
	{ name: "Marseille Card Back", image: "./marseille-deck/z00.jpg" }
];
